[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "vite"
  target = "dist"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
